### ISSUE TITLE
Rule does not ignore certain cases of URLs/paths

### ISSUE THREAD

**Issue by mghill** [IQTLabs/textlint-rule-one-sentence-per-line#3]
The example I came across was in a markdown doc, where textlint-rule-one-sentence-per-line was finding issue in the following snippet:

> The Backoffice application will be available at:  
> `https://{Application Load Balancer DNS NAME}/login?continue=/backoffice`

It wanted to split on the `?` character in the example URL. Further testing of normal prose in code spans also showed it was not skipped.

I would expect a rule to ignore things that are addresses or paths, and to ignore things in `code spans`. This could either be added as a default, or a settings option could be supported in .textlintrc either to toggle this behaviour or in a general case to permit pattern matched skipping.

**Comment by Benjamin-Lee** [comment]
Good catch! Let me think about how to fix that

**Comment by Benjamin-Lee** [comment]
I'm not going to lie: I'm not sure how to fix this. I think code spans would have to be detected, removed prior to sentence splitting, and then reinserted when fixing. Maybe @azu can take a look, since he wrote both sentence-splitter and textlint?

**Comment by azu** [comment]
https://sentence-splitter.netlify.app/#The%20Backoffice%20application%20will%20be%20available%20at%3A%0Ahttps%3A%2F%2F%7BApplication%20Load%20Balancer%20DNS%20NAME%7D%2Flogin%3Fcontinue%3D%2Fbackoffice%0A

I confirm that [sentence-splitter](https://github.com/azu/sentence-splitter) split `?` in the URL-like string.
It seem [sentence-splitter](https://github.com/azu/sentence-splitter)'s bug.
Can you create an issue to https://github.com/azu/sentence-splitter ?

Workaround: code `` `URL` ``  or link `<URL>`

> The Backoffice application will be available at:
> `https://{Application Load Balancer DNS NAME}/login?continue=/backoffice`

**Comment by mghill** [comment]
@azu in the example, I had already used the code `URL` workaround & that also did not work. We will go forward with wrapping it in tags, but I still think it is a bug, right?

**Comment by azu** [comment]
> I still think it is a bug, right?

Ah, I figure out.

textlint-rule-one-sentence-per-line should use `splitAST` instead of `split`.
`splitAST` treat `code` as code node and it does not split the `code?code`

https://github.com/IQTLabs/textlint-rule-one-sentence-per-line/blob/7db33c0565908f30adc405793e1fabb5852d5d3b/src/index.js#L46-L47

```js 
      const text = getSource(node) // <= convert node to plain text
      const split = splitter.split(text) // <= create sentences from text
```

→

```js
      const split = splitter.splitAST(text) // <= create sentences from TxtNode
```

**Comment by mghill** [comment]
Sorry, put this down when it wasn't working - just came back to it.
I absolutely do not have JS/TS skill, but fiddled with it in my local env and can kinda hack a work with another line, in `/lib/index.js`:

```Javascript
var temp_split = splitter.splitAST(node);
var split = temp_split.children; // if there is only one sentence in the line, return early it's following sembr```

I don't want to mess up a well written JS project with a fairly blind/uninformed PR, but your advice helped, thank you.
